server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /remotion/ {
        proxy_pass http://remotion-studio:3600/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://backend:8500;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /static/ {
        proxy_pass http://backend:8500;
        proxy_set_header Host $host;
    }

    location /media/ {
        proxy_pass http://backend:8500;
        proxy_set_header Host $host;
    }
}
